// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.25.0
// source: icmp.proto

package icmp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Probe_IPv int32

const (
	Probe_DEFAULT Probe_IPv = 0
	Probe_IPV4    Probe_IPv = 4
	Probe_IPV6    Probe_IPv = 6
	Probe_BOTH    Probe_IPv = 10
)

// Enum value maps for Probe_IPv.
var (
	Probe_IPv_name = map[int32]string{
		0:  "DEFAULT",
		4:  "IPV4",
		6:  "IPV6",
		10: "BOTH",
	}
	Probe_IPv_value = map[string]int32{
		"DEFAULT": 0,
		"IPV4":    4,
		"IPV6":    6,
		"BOTH":    10,
	}
)

func (x Probe_IPv) Enum() *Probe_IPv {
	p := new(Probe_IPv)
	*p = x
	return p
}

func (x Probe_IPv) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Probe_IPv) Descriptor() protoreflect.EnumDescriptor {
	return file_icmp_proto_enumTypes[0].Descriptor()
}

func (Probe_IPv) Type() protoreflect.EnumType {
	return &file_icmp_proto_enumTypes[0]
}

func (x Probe_IPv) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Probe_IPv.Descriptor instead.
func (Probe_IPv) EnumDescriptor() ([]byte, []int) {
	return file_icmp_proto_rawDescGZIP(), []int{0, 0}
}

// ICMP Probe
type Probe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host        string    `protobuf:"bytes,10,opt,name=Host,json=host,proto3" json:"Host,omitempty"`
	IPversion   Probe_IPv `protobuf:"varint,15,opt,name=IPversion,json=ipversion,proto3,enum=probe.Probe_IPv" json:"IPversion,omitempty"`
	PayloadSize int32     `protobuf:"varint,20,opt,name=PayloadSize,json=payload_size,proto3" json:"PayloadSize,omitempty"`
}

func (x *Probe) Reset() {
	*x = Probe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icmp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Probe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Probe) ProtoMessage() {}

func (x *Probe) ProtoReflect() protoreflect.Message {
	mi := &file_icmp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Probe.ProtoReflect.Descriptor instead.
func (*Probe) Descriptor() ([]byte, []int) {
	return file_icmp_proto_rawDescGZIP(), []int{0}
}

func (x *Probe) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Probe) GetIPversion() Probe_IPv {
	if x != nil {
		return x.IPversion
	}
	return Probe_DEFAULT
}

func (x *Probe) GetPayloadSize() int32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

var File_icmp_proto protoreflect.FileDescriptor

var file_icmp_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x69, 0x63, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x22, 0xa0, 0x01, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x12, 0x2e, 0x0a, 0x09, 0x49, 0x50, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x50, 0x72, 0x6f,
	0x62, 0x65, 0x2e, 0x49, 0x50, 0x76, 0x52, 0x09, 0x69, 0x70, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x21, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0x30, 0x0a, 0x03, 0x49, 0x50, 0x76, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x50, 0x56, 0x34,
	0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x50, 0x56, 0x36, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04,
	0x42, 0x4f, 0x54, 0x48, 0x10, 0x0a, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x69, 0x6e, 0x63, 0x6f, 0x6c, 0x6c, 0x2f, 0x76, 0x69, 0x67,
	0x69, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2f, 0x69, 0x63, 0x6d,
	0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_icmp_proto_rawDescOnce sync.Once
	file_icmp_proto_rawDescData = file_icmp_proto_rawDesc
)

func file_icmp_proto_rawDescGZIP() []byte {
	file_icmp_proto_rawDescOnce.Do(func() {
		file_icmp_proto_rawDescData = protoimpl.X.CompressGZIP(file_icmp_proto_rawDescData)
	})
	return file_icmp_proto_rawDescData
}

var file_icmp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_icmp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_icmp_proto_goTypes = []interface{}{
	(Probe_IPv)(0), // 0: probe.Probe.IPv
	(*Probe)(nil),  // 1: probe.Probe
}
var file_icmp_proto_depIdxs = []int32{
	0, // 0: probe.Probe.IPversion:type_name -> probe.Probe.IPv
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_icmp_proto_init() }
func file_icmp_proto_init() {
	if File_icmp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_icmp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Probe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_icmp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_icmp_proto_goTypes,
		DependencyIndexes: file_icmp_proto_depIdxs,
		EnumInfos:         file_icmp_proto_enumTypes,
		MessageInfos:      file_icmp_proto_msgTypes,
	}.Build()
	File_icmp_proto = out.File
	file_icmp_proto_rawDesc = nil
	file_icmp_proto_goTypes = nil
	file_icmp_proto_depIdxs = nil
}
